# Generated by Django 4.1.7 on 2023-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='enrollment_no',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
